# Generated by Django 5.2.17 on 2026-09-09 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('SILAGE', 'Silage'), ('FEED', 'Animal Feed')], max_length=16)),
                ('material_type', models.CharField(choices=[('GREEN_FODDER', 'Green Fodder'), ('DRY_FODDER', 'Dry Fodder'), ('SILAGE', 'Silage'), ('CONCENTRATE_FEED', 'Concentrate Feed'), ('OTHER', 'Other')], max_length=32)),
                ('material_type_other', models.CharField(blank=True, max_length=100)),
                ('storage_duration_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SAVED', 'Saved')], default='DRAFT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.inspection')),
            ],
        ),
    ]
