# Generated by Django 5.2.17 on 2026-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='followup_qa',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
