# Generated by Django 5.2.17 on 2026-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspection_followup_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='farmer_observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='humidity_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='moisture_exposure',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='storage_condition',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=8),
        ),
        migrations.AddField(
            model_name='inspection',
            name='temperature_celsius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionimage',
            name='image_type',
            field=models.CharField(choices=[('FRONT_GENERAL', 'Front / General'), ('SIDE_DEPTH', 'Side / Depth'), ('MACRO', 'Macro'), ('STORAGE', 'Storage')], default='FRONT_GENERAL', max_length=16),
        ),
    ]
