# Generated by Django 5.2.17 on 2026-09-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspection_farmer_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/processed/%Y/%m/'),
        ),
    ]
