# Generated by Django 5.2.17 on 2026-09-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['created_at']},
        ),
    ]
