# Generated by Django 5.2.17 on 2026-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='action_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SELL_FEED', 'Sell / Waste Disposal'), ('LAB_TEST', 'Lab Testing'), ('VET_SUPPORT', 'Veterinary Support')], default='GENERAL', max_length=16),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='urgency',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate Action'), ('CORRECTIVE', 'Corrective Action'), ('VERIFICATION', 'Verification')], default='CORRECTIVE', max_length=16),
        ),
    ]
