# Generated by Django 5.2.17 on 2026-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='total_cattle',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
