# Generated by Django 5.2.17 on 2026-09-12 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_total_cattle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo'), ('goat', 'Goat')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
                ('milk_liters_per_day', models.PositiveIntegerField(default=0)),
                ('lactation_stage', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
